### PR TITLE
Add data platform component

### PR DESCRIPTION
**Pull request by fbertsch**

### CODE REVIEW

**Comment by fbertsch** [comment]
@globau, can you take a look?

**Comment by globau** [comment]
This tool is coupled with [Firefox's triage process](https://firefox-source-docs.mozilla.org/bug-mgmt/policies/triage-bugzilla.html) - does the `Data Platform and Tools` product follow this?

If so, we'll also need to add it to [Bugzilla](https://github.com/mozilla-bteam/bmo/blob/268a7a7f7dd35d3b7b20b9dc5952f99a9b6667fe/extensions/BMO/lib/Data.pm#L171) and [auto-nag](https://github.com/mozilla/relman-auto-nag/blob/0c7b1c4c5e26dd9951044ced62da7ec1bbdb887d/auto_nag/scripts/configs/tools.json#L36) to ensure the systems are in agreement about if a bug is triaged or not.

**Comment by fbertsch** [comment]
Hmm these are good questions. Is there a description of what enabling `mozilla-bteam/bmo` and auto-nag are?

**Comment by globau** [comment]
It basically means that you'll commit to following the Firefox triage process.

For Bugzilla this will soon result in a slightly different set of rules around what fields can, cannot, and must be set in order for a bug to be both submitted and considered as triaged.  It also means your components must have a triage owner who is responsible for bug triage.

For auto-nag, that's our escalation bot; it'll set needinfos according to ensure bugs are managed appropriately.

Adding products to Triage Center that do not follow the Firefox triage process will become increasingly problematic as we tweak the process over time.  eg. we will be moving off using the Severity field as a signal for "is triaged" (as per [this document](https://docs.google.com/document/d/1ZwbTWIbgL7UGSkE65luKFC-bj-BOAQhNg_tvbpyl-P8/)).

**Comment by fbertsch** [comment]
Thanks for the description, @globau. It sounds like this isn't the right fit - we don't have quite the same requirements as Firefox. I have been running triage-center locally though and using it to help triage this component. If it's out of the question to include it here without the additional requirements (e.g. auto-nag), I might try and see if I can simply use bugzilla search (or continue running locally 😄 )

**Pull request closed without merging**
